In [ ]:
    create table detalhe_votacao_secao(
    DATA_GERACAO STRING,
    HORA_GERACAO STRING,
    ANO_ELEICAO STRING,
    NUM_TURNO STRING,
    DESCRICAO_ELEICAO STRING,
    SIGLA_UF STRING,
    SIGLA_UE STRING,
    CODIGO_MUNICIPIO STRING,
    NOME_MUNICIPIO STRING,
    NUMERO_ZONA STRING,
    NUMERO_SECAO STRING,
    CODIGO_CARGO STRING,
    DESCRICAO_CARGO STRING,
    QTD_APTOS STRING,
    QTD_COMPARECIMENTO STRING,
    QTD_ABSTENCOES STRING,
    QT_VOTOS_NOMINAIS STRING,
    QT_VOTOS_BRANCOS STRING,
    QT_VOTOS_NULOS STRING,
    QT_VOTOS_LEGENDA STRING,
    QT_VOTOS_ANULADOS_APU_SEP STRING) 
    ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
    WITH SERDEPROPERTIES (
    'separatorChar' = '\;',
    'quoteChar'     = '\"'
    )
    STORED AS TEXTFILE;

    Alter table detalhe_votacao_secao set location 's3://datascience2016/data/gzip/detalhe_votacao_secao';
    
    
    
Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2016/13/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2016"
and d.CODIGO_CARGO="13"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;


Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2016/11/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2016"
and d.CODIGO_CARGO="11"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;




Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2012/13/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2012"
and d.CODIGO_CARGO="13"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;


Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2012/11/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2012"
and d.CODIGO_CARGO="11"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;




Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2008/13/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2008"
and d.CODIGO_CARGO="13"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;


Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2008/11/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2008"
and d.CODIGO_CARGO="11"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;




Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2004/13/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2004"
and d.CODIGO_CARGO="13"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;


Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2004/11/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2004"
and d.CODIGO_CARGO="11"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;




Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2004/11/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2004"
and d.CODIGO_CARGO="11"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;





Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2014/1/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2014"
and d.CODIGO_CARGO="1"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;


Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2014/3/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2014"
and d.CODIGO_CARGO="3"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;

Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2014/5/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2014"
and d.CODIGO_CARGO="5"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;

Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2014/6/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2014"
and d.CODIGO_CARGO="6"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;
    

Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2014/7/';
INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2014"
and d.CODIGO_CARGO="7"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;






Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2010/1/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2010"
and d.CODIGO_CARGO="1"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;


Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2010/3/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2010"
and d.CODIGO_CARGO="3"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;

Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2010/5/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2010"
and d.CODIGO_CARGO="5"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;

Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2010/6/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2010"
and d.CODIGO_CARGO="6"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;
    

Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2010/7/';
INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2010"
and d.CODIGO_CARGO="7"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;
    
    
    
    Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2006/1/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2006"
and d.CODIGO_CARGO="1"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;


Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2006/3/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2006"
and d.CODIGO_CARGO="3"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;

Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2006/5/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2006"
and d.CODIGO_CARGO="5"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;

Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2006/6/';

INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2006"
and d.CODIGO_CARGO="6"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;
    

Alter table output_consolidado set location 's3://datascience2016/data/gzip/output/detalhe/2006/7/';
INSERT OVERWRITE TABLE output_consolidado
select
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
sum(cast(QTD_APTOS AS INT)) as QTD_APTOS,
sum(cast(QTD_COMPARECIMENTO AS INT)) as QTD_COMPARECIMENTO,
sum(cast(QTD_ABSTENCOES AS INT)) as QTD_ABSTENCOES,
sum(cast(QT_VOTOS_NOMINAIS AS INT)) as QT_VOTOS_NOMINAIS,
sum(cast(QT_VOTOS_BRANCOS AS INT)) as QT_VOTOS_BRANCOS,
sum(cast(QT_VOTOS_NULOS AS INT)) as QT_VOTOS_NULOS,
sum(cast(QT_VOTOS_LEGENDA AS INT)) as QT_VOTOS_LEGENDA,
sum(cast(QT_VOTOS_ANULADOS_APU_SEP AS INT)) as QT_VOTOS_ANULADOS_APU_SEP,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA 
from detalhe_votacao_secao as d join aux_municipio as m 
on 
d.CODIGO_MUNICIPIO=m.CODIGO_MUNICIPIO
and d.ANO_ELEICAO="2006"
and d.CODIGO_CARGO="7"
group by
d.ANO_ELEICAO,
d.NUM_TURNO,
d.DESCRICAO_ELEICAO,
d.CODIGO_CARGO,
d.DESCRICAO_CARGO,
m.CODIGO_MACRO,
m.NOME_MACRO,
m.UF,
m.NOME_UF,
m.CODIGO_MESO,
m.NOME_MESO,
m.CODIGO_MICRO,
m.NOME_MICRO,
d.CODIGO_MUNICIPIO,
m.NOME_MUNICIPIO,
d.NUMERO_ZONA;