# Análise dos Candidatos do ano 2000

Foi percebido que a tabela detalhe candidato de 2000 possui 4 vezes mais linhas do que as dos outros anos. 

#Quantidade de linhas
**1.632.750**

#Quantidade de linhas quando se agrega por título de eleitor
**412.785**

#Quantidade de linhas quando se agrega por nome do candidato
**385.309**

#Quantidade de linhas quando se agrega por número votável e sigla UE 
**413.403**

#Linhas com o titulo de eleitor não informado:
``` mysql
    select count(*) from detalhe_candidato_1998_2012 where NUM_TITULO_ELEITORAL_CANDIDATO='#NI#'AND ANO_ELEICAO="2000"
```
#### Resultado: 3922 linhas 

#Linhas com o mesmo titulo de eleitor.

### Verificando o número ocorrencias do mesmo titulo de eleitor no AN

``` mysql 
    select ANO_ELEICAO,  
        sum(if(ocorrencia=1, 1, 0)),
        sum(if(ocorrencia=2, 1, 0)),
        sum(if(ocorrencia=3, 1, 0)),
        sum(if(ocorrencia=4, 1, 0)),
        sum(if(ocorrencia>4, 1, 0)) 
    from (
        select count(*) as ocorrencia,
        NUM_TITULO_ELEITORAL_CANDIDATO,
        ANO_ELEICAO 
        from detalhe_candidato_1998_2012 
        group by ANO_ELEICAO,NUM_TITULO_ELEITORAL_CANDIDATO
    ) as c group by ANO_ELEICAO; 

```

### Resultado

<table><thead>
<tr><th>ANO_ELEICAO</th><th>1x</th><th>2x</th><th>3x</th><th>4x</th><th>5x +</th></tr></thead>
<tbody>

<tr><td>1998</td><td>14782</td><td>133</td><td>3</td><td>8</td><td>1</td></tr>
<tr><td>2000</td><td>0</td><td>134614</td><td>0</td><td>155002</td><td>123169</td></tr>
<tr><td>2002</td><td>18808</td><td>223</td><td>2</td><td>0</td><td>1</td></tr>
<tr><td>2004</td><td>398965</td><td>1261</td><td>15</td><td>0</td><td>2</td></tr>
<tr><td>2006</td><td>20436</td><td>174</td><td>2</td><td>0</td><td>0</td></tr>
<tr><td>2008</td><td>381495</td><td>1482</td><td>18</td><td>2</td><td>1</td></tr>
<tr><td>2010</td><td>22072</td><td>248</td><td>3</td><td>0</td><td>0</td></tr>
<tr><td>2012</td><td>478342</td><td>2650</td><td>61</td><td>0</td><td>0</td></tr>
<tr><td>2014</td><td>25829</td><td>192</td><td>3</td><td>0</td><td>0</td></tr>
<tr><td>2016</td><td>494881</td><td>1186</td><td>8</td><td>0</td><td>0</td></tr>
</tbody>

</table>

## Alguns exemplos de linhas com mais de 5 resultados.

``` mysql
select * from (
select c.ANO_ELEICAO, c.NUM_TITULO_ELEITORAL_CANDIDATO
from (
select count(*) as ocorrencia,
NUM_TITULO_ELEITORAL_CANDIDATO,
ANO_ELEICAO 
from detalhe_candidato_1998_2012 
group by ANO_ELEICAO,NUM_TITULO_ELEITORAL_CANDIDATO
) as c where c.ocorrencia>4 AND c.ANO_ELEICAO='2000') as m 
join detalhe_candidato_1998_2012 as a 
on  a.NUM_TITULO_ELEITORAL_CANDIDATO=m.NUM_TITULO_ELEITORAL_CANDIDATO and 
a.NUM_TITULO_ELEITORAL_CANDIDATO<>'#NI#' 
order by a.NUM_TITULO_ELEITORAL_CANDIDATO limit 200; 

```

In [7]:
import pandas as pd
cand_h_1998_2010 = ["ANO_ELEICAO","-","DATA_GERACAO",
"HORA_GERACAO",
"ANO_ELEICAO",
"NUM_TURNO",
"DESCRICAO_ELEICAO",
"SIGLA_UF",
"SIGLA_UE",
"DESCRICAO_UE",
"CODIGO_CARGO",
"DESCRICAO_CARGO",
"NOME_CANDIDATO",
"SEQUENCIAL_CANDIDATO",
"NUMERO_CANDIDATO",
"CPF_CANDIDATO",
"NOME_URNA_CANDIDATO",
"COD_SITUACAO_CANDIDATURA",
"DES_SITUACAO_CANDIDATURA",
"NUMERO_PARTIDO",
"SIGLA_PARTIDO",
"NOME_PARTIDO",
"CODIGO_LEGENDA",
"SIGLA_LEGENDA",
"COMPOSICAO_LEGENDA",
"NOME_LEGENDA",
"CODIGO_OCUPACAO",
"DESCRICAO_OCUPACAO",
"DATA_NASCIMENTO",
"NUM_TITULO_ELEITORAL_CANDIDATO",
"IDADE_DATA_ELEICAO",
"CODIGO_SEXO",
"DESCRICAO_SEXO",
"COD_GRAU_INSTRUCAO",
"DESCRICAO_GRAU_INSTRUCAO",
"CODIGO_ESTADO_CIVIL",
"DESCRICAO_ESTADO_CIVIL",
"CODIGO_NACIONALIDADE",
"DESCRICAO_NACIONALIDADE",
"SIGLA_UF_NASCIMENTO",
"CODIGO_MUNICIPIO_NASCIMENTO",
"NOME_MUNICIPIO_NASCIMENTO",
"DESPESA_MAX_CAMPANHA",
"COD_SIT_TOT_TURNO",
"DESC_SIT_TOT_TURNO"]
candidatos = pd.read_csv("data/candidatos_repetidos_2000.csv",error_bad_lines=False,names=cand_h_1998_2010)

## Nomes repetidos

In [12]:
a = candidatos[["SIGLA_UF","DATA_GERACAO","HORA_GERACAO","NUMERO_CANDIDATO","NUM_TITULO_ELEITORAL_CANDIDATO","NOME_CANDIDATO","NOME_URNA_CANDIDATO","ANO_ELEICAO"]]
a = a[a["NUM_TITULO_ELEITORAL_CANDIDATO"]!='-1']
a

,SIGLA_UF,DATA_GERACAO,HORA_GERACAO,NUMERO_CANDIDATO,NUM_TITULO_ELEITORAL_CANDIDATO,NOME_CANDIDATO,NOME_URNA_CANDIDATO,ANO_ELEICAO
0,CE,25/11/2016,18:23:17,41919,0 0335760744,VERA LÚCIA VERAS BEZERRA,VERA LÚCIA VERAS BEZERRA,2000
2,CE,25/11/2016,18:23:17,41919,0 0335760744,VERA LÚCIA VERAS BEZERRA,VERA LÚCIA VERAS BEZERRA,2000
3,CE,25/11/2016,18:23:17,41919,0 0335760744,VERA LÚCIA VERAS BEZERRA,VERA VERAS,2000
4,CE,25/11/2016,18:23:17,41919,0 0335760744,VERA LÚCIA VERAS BEZERRA,VERA VERAS,2000
6,SC,25/11/2016,18:24:55,13002,000000000222,OOOOOO,YYYY,2000
7,SC,25/11/2016,18:24:55,13002,000000000222,OOOOOO,TTT,2000
8,SC,25/11/2016,18:24:55,13002,000000000222,OOOOOO,TTT,2000
9,SC,25/11/2016,18:24:55,13002,000000000222,OOOOOO,WWWW,2000
10,SC,25/11/2016,18:24:55,13002,000000000222,OOOOOO,YYYY,2000
11,SC,25/11/2016,18:24:55,13002,000000000222,OOOOOO,WWWW,2000
12,BA,25/11/2016,18:23:08,25008,000000000302,CARMEM LUCIA FERREIRA,CAMINHA,2000
13,GO,25/11/2016,18:23:25,151,000000000302,RAUL SEIXAS,NaN,2000
18,BA,25/11/2016,18:23:08,25002,000000000302,WILMA ALVES DA CUNHA,VILMA,2000
19,BA,25/11/2016,18:23:08,25001,000000000302,LUIS CARLOS GOMIDE,LULU,2000
20,BA,25/11/2016,18:23:08,25001,000000000302,LUIS CARLOS GOMIDE,LUIS,2000
21,BA,25/11/2016,18:23:08,25001,000000000302,LUIS CARLOS GOMIDE,CACA,2000
23,BA,25/11/2016,18:23:08,15001,000000000302,MARIA SILVEIRA ALENCAR,MARIA SILVEIRA,2000
26,BA,25/11/2016,18:23:08,11001,000000000302,HERCULES GONGALVES LIMA,HERCULES GONGALVES,2000
27,BA,25/11/2016,18:23:08,11001,000000000302,HERCULES GONGALVES LIMA,HERCULES,2000
28,BA,25/11/2016,18:23:08,11001,000000000302,HERCULES GONGALVES LIMA,GONGALVES,2000
29,BA,25/11/2016,18:23:08,221,MASCULINO,GONGALVES DIAS,22,2000
31,BA,25/11/2016,18:23:08,2500000512312,2,GERALDO PEDREIRA MENEZES,1,2000
34,BA,25/11/2016,18:23:08,15001,000000000302,MARIA SILVEIRA ALENCAR,MARIA SILVEIRA,2000
35,PE,25/11/2016,18:24:17,11,0,TESTE,TTPENDENTE,2000
38,GO,25/11/2016,18:23:25,45625,000000000302,SEU CHICO,CHICO,2000
39,BA,25/11/2016,18:23:08,11001,000000000302,HERCULES GONGALVES LIMA,HERCULES GONGALVES,2000
40,BA,25/11/2016,18:23:08,11001,000000000302,HERCULES GONGALVES LIMA,HERCULES,2000
41,BA,25/11/2016,18:23:08,11001,000000000302,HERCULES GONGALVES LIMA,GONGALVES,2000
42,BA,25/11/2016,18:23:08,221,MASCULINO,GONGALVES DIAS,22,2000
43,GO,25/11/2016,18:23:25,151,000000000302,RAUL SEIXAS,NaN,2000
...,...,...,...,...,...,...,...,...
169,RO,25/11/2016,18:24:43,23222,000002832364,HELIA BURGOS DE CHAVES,LINDA DO FOTÓGRAFO,2000
170,PI,25/11/2016,18:24:22,25606,000002971562,ANGELA MARIA MACHADO DE ANDRADE MATEUS,ANGELA MARIA,2000
171,PI,25/11/2016,18:24:22,25606,000002971562,ANGELA MARIA MACHADO DE ANDRADE MATEUS,ANGELA MARIA MACHADO,2000
172,PI,25/11/2016,18:24:22,25606,000002971562,ANGELA MARIA MACHADO DE ANDRADE MATEUS,ANGELA,2000
173,PI,15/07/2016,19:24:06,55123,000002971562,ANGELA MARIA MACHADO DE ANDRADE MATEUS,ANGELA,2000
174,PI,25/11/2016,18:24:22,25606,000002971562,ANGELA MARIA MACHADO DE ANDRADE MATEUS,ANGELA,2000
175,PI,25/11/2016,18:24:22,25606,000002971562,ANGELA MARIA MACHADO DE ANDRADE MATEUS,ANGELA MARIA,2000
176,PI,26/04/2017,19:29:07,14789,000002971562,ANGELA MARIA MACHADO DE ANDRADE MATEUS,ANGELA,2000
177,PI,16/12/2016,18:44:34,25124,000002971562,ANGELA MARIA MACHADO DE ANDRADE MATEUS,ANGELA,2000
178,PI,29/02/2016,19:10:36,25124,000002971562,ÂNGELA MARIA MACHADO DE ANDRADE MATEUS,ÂNGELA,2000
179,PI,25/11/2016,18:24:22,25606,000002971562,ANGELA MARIA MACHADO DE ANDRADE MATEUS,ANGELA MARIA MACHADO,2000
180,AC,25/11/2016,18:23:01,13110,000003142402,NONATA MARTINS QUEIROZ,NONATA MARTINS,2000
181,AC,25/11/2016,18:23:01,13110,000003142402,NONATA MARTINS QUEIROZ,NONATA QUEIROZ,2000
182,AC,25/11/2016,18:23:01,13110,000003142402,NONATA MARTINS QUEIROZ,NONATA MARTINS,2000
183,AC,25/11/2016,18:23:01,13110,000003142402,NONATA MARTINS QUEIROZ,NONATA,2000
184,AC,25/11/2016,18:23:01,13110,000003142402,NONATA MARTINS QUEIROZ,NONATA,2000
185,AC,25/11/2016,18:23:01,13110,000003142402,NONATA MARTINS QUEIROZ,NONATA QUEIROZ,2000
186,AC,16/12/2016,18:44:11,15677,000003142402,NONATA MARTINS QUEIROZ,NONATA MARTINS QUEIROZ,2000
187,PA,25/11/2016,18:24:08,11654,000003321384,GERVASIO DA CUNHA MORGADO,GERVÁSIO MORGADO,2000
188,PA,29/02/2016,19:09:17,22123,000003321384,GERVASIO DA CUNHA MORGADO,MORGADO,2000
189,PA,19/10/2015,19:03:21,00416290272,2,GERVASIO DA CUNHA MORGADO,2,2000
190,PA,16/12/2016,18:44:29,22321,18081946,GERVASIO DA CUNHA MORGADO,MORGADO,2000
191,PA,26/04/2017,19:29:07,22123,000003321384,GERVASIO DA CUNHA MORGADO,MORGADO,2000
193,PA,25/11/2016,18:24:08,11654,000003321384,GERVASIO DA CUNHA MORGADO,GERVÁSIO MORGADO,2000
194,PA,25/11/2016,18:24:08,11654,000003321384,GERVASIO DA CUNHA MORGADO,MORGADO,2000
195,PA,19/10/2015,19:03:24,22321,000003321384,GERVASIO DA CUNHA MORGADO,MORGADO,2000
196,PA,19/10/2015,19:03:19,00416290272,297,GERVASIO DA CUNHA MORGADO,2,2000
197,PA,25/11/2016,18:24:08,11654,000003321384,GERVASIO DA CUNHA MORGADO,MORGADO,2000
198,PA,25/11/2016,18:24:08,11654,000003321384,GERVASIO DA CUNHA MORGADO,GERVÁSIO,2000
199,PA,25/11/2016,18:24:08,11654,000003321384,GERVASIO DA CUNHA MORGADO,GERVÁSIO,2000