In [1]:
from web.cepesp.athena.builders import AthenaBuilder

In [2]:
def query(**options):
    builder = AthenaBuilder(**options)
    print(builder.build())

In [3]:
query(table='votos', years=[2014], job=7, reg=4, brancos=True, uf_filter='CE')

SELECT NUMERO_CANDIDATO AS NUMERO_CANDIDATO, ID_LEGENDA AS ID_LEGENDA, UF AS UF, NOME_UF AS NOME_UF, ANO_ELEICAO AS ANO_ELEICAO, DESCRICAO_CARGO AS DESCRICAO_CARGO, ID_CANDIDATO AS ID_CANDIDATO, SIGLA_UE AS SIGLA_UE, CODIGO_MACRO AS CODIGO_MACRO, CODIGO_CARGO AS CODIGO_CARGO, DATA_GERACAO AS DATA_GERACAO, NOME_MESO AS NOME_MESO, NOME_MACRO AS NOME_MACRO, CODIGO_MESO AS CODIGO_MESO, NUM_TURNO AS NUM_TURNO, HORA_GERACAO AS HORA_GERACAO, DESCRICAO_ELEICAO AS DESCRICAO_ELEICAO, SUM(QTDE_VOTOS) AS QTDE_VOTOS FROM votes_meso WHERE p_ano IN ('2014') AND (p_cargo = '7' OR p_cargo = '8') AND UF = 'CE' GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17 ORDER BY UF ASC, NUM_TURNO ASC, NUMERO_CANDIDATO ASC

In [4]:
query(table='candidatos', years=[2014], job=1, only_elected=True)

SELECT ID_CANDIDATO AS ID_CANDIDATO, DATA_GERACAO AS DATA_GERACAO, HORA_GERACAO AS HORA_GERACAO, ANO_ELEICAO AS ANO_ELEICAO, NUM_TURNO AS NUM_TURNO, DESCRICAO_ELEICAO AS DESCRICAO_ELEICAO, SIGLA_UF AS SIGLA_UF, SIGLA_UE AS SIGLA_UE, DESCRICAO_UE AS DESCRICAO_UE, CODIGO_CARGO AS CODIGO_CARGO, DESCRICAO_CARGO AS DESCRICAO_CARGO, NUMERO_PARTIDO AS NUMERO_PARTIDO, SIGLA_PARTIDO AS SIGLA_PARTIDO, NOME_CANDIDATO AS NOME_CANDIDATO, NUMERO_CANDIDATO AS NUMERO_CANDIDATO, CPF_CANDIDATO AS CPF_CANDIDATO, NOME_URNA_CANDIDATO AS NOME_URNA_CANDIDATO, COD_SITUACAO_CANDIDATURA AS COD_SITUACAO_CANDIDATURA, DES_SITUACAO_CANDIDATURA AS DES_SITUACAO_CANDIDATURA, NOME_PARTIDO AS NOME_PARTIDO, CODIGO_LEGENDA AS CODIGO_LEGENDA, SIGLA_LEGENDA AS SIGLA_LEGENDA, COMPOSICAO_LEGENDA AS COMPOSICAO_LEGENDA, NOME_COLIGACAO AS NOME_COLIGACAO, CODIGO_OCUPACAO AS CODIGO_OCUPACAO, DESCRICAO_OCUPACAO AS DESCRICAO_OCUPACAO, DATA_NASCIMENTO AS DATA_NASCIMENTO, NUM_TITULO_ELEITORAL_CANDIDATO AS NUM_TITULO_ELEITORAL_CANDIDATO, IDADE_DATA_ELEICAO AS IDADE_DATA_ELEICAO, CODIGO_SEXO AS CODIGO_SEXO, DESCRICAO_SEXO AS DESCRICAO_SEXO, COD_GRAU_INSTRUCAO AS COD_GRAU_INSTRUCAO, DESCRICAO_GRAU_INSTRUCAO AS DESCRICAO_GRAU_INSTRUCAO, CODIGO_ESTADO_CIVIL AS CODIGO_ESTADO_CIVIL, DESCRICAO_ESTADO_CIVIL AS DESCRICAO_ESTADO_CIVIL, CODIGO_COR_RACA AS CODIGO_COR_RACA, DESCRICAO_COR_RACA AS DESCRICAO_COR_RACA, CODIGO_NACIONALIDADE AS CODIGO_NACIONALIDADE, DESCRICAO_NACIONALIDADE AS DESCRICAO_NACIONALIDADE, SIGLA_UF_NASCIMENTO AS SIGLA_UF_NASCIMENTO, CODIGO_MUNICIPIO_NASCIMENTO AS CODIGO_MUNICIPIO_NASCIMENTO, NOME_MUNICIPIO_NASCIMENTO AS NOME_MUNICIPIO_NASCIMENTO, DESPESA_MAX_CAMPANHA AS DESPESA_MAX_CAMPANHA, COD_SIT_TOT_TURNO AS COD_SIT_TOT_TURNO, DESC_SIT_TOT_TURNO AS DESC_SIT_TOT_TURNO, EMAIL_CANDIDATO AS EMAIL_CANDIDATO FROM candidatos AS v WHERE p_ano IN ('2014') AND (p_cargo = '1') AND v.COD_SIT_TOT_TURNO IN ('1', '2', '3') ORDER BY ANO_ELEICAO ASC, SIGLA_UF ASC, SIGLA_UE ASC, CODIGO_CARGO ASC, NUMERO_CANDIDATO ASC

In [5]:
query(table='candidatos', years=[2014], job=7, filters={
    'NOME_CANDIDATO': 'FULANO DE TAL'
})

SELECT ID_CANDIDATO AS ID_CANDIDATO, DATA_GERACAO AS DATA_GERACAO, HORA_GERACAO AS HORA_GERACAO, ANO_ELEICAO AS ANO_ELEICAO, NUM_TURNO AS NUM_TURNO, DESCRICAO_ELEICAO AS DESCRICAO_ELEICAO, SIGLA_UF AS SIGLA_UF, SIGLA_UE AS SIGLA_UE, DESCRICAO_UE AS DESCRICAO_UE, CODIGO_CARGO AS CODIGO_CARGO, DESCRICAO_CARGO AS DESCRICAO_CARGO, NUMERO_PARTIDO AS NUMERO_PARTIDO, SIGLA_PARTIDO AS SIGLA_PARTIDO, NOME_CANDIDATO AS NOME_CANDIDATO, NUMERO_CANDIDATO AS NUMERO_CANDIDATO, CPF_CANDIDATO AS CPF_CANDIDATO, NOME_URNA_CANDIDATO AS NOME_URNA_CANDIDATO, COD_SITUACAO_CANDIDATURA AS COD_SITUACAO_CANDIDATURA, DES_SITUACAO_CANDIDATURA AS DES_SITUACAO_CANDIDATURA, NOME_PARTIDO AS NOME_PARTIDO, CODIGO_LEGENDA AS CODIGO_LEGENDA, SIGLA_LEGENDA AS SIGLA_LEGENDA, COMPOSICAO_LEGENDA AS COMPOSICAO_LEGENDA, NOME_COLIGACAO AS NOME_COLIGACAO, CODIGO_OCUPACAO AS CODIGO_OCUPACAO, DESCRICAO_OCUPACAO AS DESCRICAO_OCUPACAO, DATA_NASCIMENTO AS DATA_NASCIMENTO, NUM_TITULO_ELEITORAL_CANDIDATO AS NUM_TITULO_ELEITORAL_CANDIDATO, IDADE_DATA_ELEICAO AS IDADE_DATA_ELEICAO, CODIGO_SEXO AS CODIGO_SEXO, DESCRICAO_SEXO AS DESCRICAO_SEXO, COD_GRAU_INSTRUCAO AS COD_GRAU_INSTRUCAO, DESCRICAO_GRAU_INSTRUCAO AS DESCRICAO_GRAU_INSTRUCAO, CODIGO_ESTADO_CIVIL AS CODIGO_ESTADO_CIVIL, DESCRICAO_ESTADO_CIVIL AS DESCRICAO_ESTADO_CIVIL, CODIGO_COR_RACA AS CODIGO_COR_RACA, DESCRICAO_COR_RACA AS DESCRICAO_COR_RACA, CODIGO_NACIONALIDADE AS CODIGO_NACIONALIDADE, DESCRICAO_NACIONALIDADE AS DESCRICAO_NACIONALIDADE, SIGLA_UF_NASCIMENTO AS SIGLA_UF_NASCIMENTO, CODIGO_MUNICIPIO_NASCIMENTO AS CODIGO_MUNICIPIO_NASCIMENTO, NOME_MUNICIPIO_NASCIMENTO AS NOME_MUNICIPIO_NASCIMENTO, DESPESA_MAX_CAMPANHA AS DESPESA_MAX_CAMPANHA, COD_SIT_TOT_TURNO AS COD_SIT_TOT_TURNO, DESC_SIT_TOT_TURNO AS DESC_SIT_TOT_TURNO, EMAIL_CANDIDATO AS EMAIL_CANDIDATO FROM candidatos AS v WHERE p_ano IN ('2014') AND (p_cargo = '7' OR p_cargo = '8') AND REGEXP_LIKE(LOWER(NOME_CANDIDATO), 'fulano de tal') ORDER BY ANO_ELEICAO ASC, SIGLA_UF ASC, SIGLA_UE ASC, CODIGO_CARGO ASC, NUMERO_CANDIDATO ASC

In [6]:
query(table='legendas', years=[2014], job=1, filters={
    'NOME_CANDIDATO': 'FULANO DE TAL', # Should be skipped
    'NOME_PARTIDO': 'PARTIDO TAL'
})

SELECT ID_LEGENDA AS ID_LEGENDA, DATA_GERACAO AS DATA_GERACAO, HORA_GERACAO AS HORA_GERACAO, ANO_ELEICAO AS ANO_ELEICAO, NUM_TURNO AS NUM_TURNO, DESCRICAO_ELEICAO AS DESCRICAO_ELEICAO, SIGLA_UF AS SIGLA_UF, SIGLA_UE AS SIGLA_UE, CODIGO_CARGO AS CODIGO_CARGO, DESCRICAO_CARGO AS DESCRICAO_CARGO, TIPO_LEGENDA AS TIPO_LEGENDA, NUMERO_PARTIDO AS NUMERO_PARTIDO, SIGLA_PARTIDO AS SIGLA_PARTIDO, NOME_PARTIDO AS NOME_PARTIDO, SIGLA_COLIGACAO AS SIGLA_COLIGACAO, NOME_COLIGACAO AS NOME_COLIGACAO, COMPOSICAO_COLIGACAO AS COMPOSICAO_COLIGACAO, SEQUENCIA_COLIGACAO AS SEQUENCIA_COLIGACAO FROM legendas AS v WHERE p_ano IN ('2014') AND (p_cargo = '1') AND REGEXP_LIKE(LOWER(NOME_PARTIDO), 'partido tal') ORDER BY ANO_ELEICAO ASC, SIGLA_UF ASC, SIGLA_UE ASC, CODIGO_CARGO ASC, NUMERO_PARTIDO ASC

In [7]:
query(table='tse', years=[2014], job=1, reg=5, pol=2, only_elected=True, filters={
    'NOME_CANDIDATO': 'FULANO DE TAL',
    'NOME_PARTIDO': 'PARTIDO TAL'
})

SELECT v.ANO_ELEICAO AS ANO_ELEICAO, v.NUM_TURNO AS NUM_TURNO, v.CODIGO_MICRO AS CODIGO_MICRO, v.NOME_MICRO AS NOME_MICRO, v.CODIGO_MESO AS CODIGO_MESO, v.NOME_MESO AS NOME_MESO, v.UF AS UF, v.NOME_UF AS NOME_UF, v.CODIGO_MACRO AS CODIGO_MACRO, v.NOME_MACRO AS NOME_MACRO, v.DESCRICAO_ELEICAO AS DESCRICAO_ELEICAO, c.SIGLA_UE AS SIGLA_UE, c.DESCRICAO_UE AS DESCRICAO_UE, v.CODIGO_CARGO AS CODIGO_CARGO, v.DESCRICAO_CARGO AS DESCRICAO_CARGO, IF(v.NUMERO_PARTIDO = '95', 'VOTO BRANCO', IF(v.NUMERO_PARTIDO = '96', 'VOTO NULO', c.NOME_CANDIDATO)) AS NOME_CANDIDATO, v.NUMERO_CANDIDATO AS NUMERO_CANDIDATO, c.CPF_CANDIDATO AS CPF_CANDIDATO, c.NOME_URNA_CANDIDATO AS NOME_URNA_CANDIDATO, c.COD_SITUACAO_CANDIDATURA AS COD_SITUACAO_CANDIDATURA, c.DES_SITUACAO_CANDIDATURA AS DES_SITUACAO_CANDIDATURA, l.NUMERO_PARTIDO AS NUMERO_PARTIDO, IF(v.NUMERO_PARTIDO = '95', 'VOTO BRANCO', IF(v.NUMERO_PARTIDO = '96', 'VOTO NULO', l.SIGLA_PARTIDO)) AS SIGLA_PARTIDO, IF(v.NUMERO_PARTIDO = '95', 'VOTO BRANCO', IF(v.NUMERO_PARTIDO = '96', 'VOTO NULO', l.NOME_PARTIDO)) AS NOME_PARTIDO, c.CODIGO_LEGENDA AS CODIGO_LEGENDA, c.SIGLA_LEGENDA AS SIGLA_LEGENDA, c.COMPOSICAO_LEGENDA AS COMPOSICAO_LEGENDA, c.CODIGO_OCUPACAO AS CODIGO_OCUPACAO, c.DESCRICAO_OCUPACAO AS DESCRICAO_OCUPACAO, c.DATA_NASCIMENTO AS DATA_NASCIMENTO, c.NUM_TITULO_ELEITORAL_CANDIDATO AS NUM_TITULO_ELEITORAL_CANDIDATO, c.IDADE_DATA_ELEICAO AS IDADE_DATA_ELEICAO, c.CODIGO_SEXO AS CODIGO_SEXO, c.DESCRICAO_SEXO AS DESCRICAO_SEXO, c.COD_GRAU_INSTRUCAO AS COD_GRAU_INSTRUCAO, c.DESCRICAO_GRAU_INSTRUCAO AS DESCRICAO_GRAU_INSTRUCAO, c.CODIGO_ESTADO_CIVIL AS CODIGO_ESTADO_CIVIL, c.DESCRICAO_ESTADO_CIVIL AS DESCRICAO_ESTADO_CIVIL, c.CODIGO_COR_RACA AS CODIGO_COR_RACA, c.DESCRICAO_COR_RACA AS DESCRICAO_COR_RACA, c.CODIGO_NACIONALIDADE AS CODIGO_NACIONALIDADE, c.DESCRICAO_NACIONALIDADE AS DESCRICAO_NACIONALIDADE, c.SIGLA_UF_NASCIMENTO AS SIGLA_UF_NASCIMENTO, c.CODIGO_MUNICIPIO_NASCIMENTO AS CODIGO_MUNICIPIO_NASCIMENTO, c.NOME_MUNICIPIO_NASCIMENTO AS NOME_MUNICIPIO_NASCIMENTO, c.DESPESA_MAX_CAMPANHA AS DESPESA_MAX_CAMPANHA, c.COD_SIT_TOT_TURNO AS COD_SIT_TOT_TURNO, c.DESC_SIT_TOT_TURNO AS DESC_SIT_TOT_TURNO, c.EMAIL_CANDIDATO AS EMAIL_CANDIDATO, l.TIPO_LEGENDA AS TIPO_LEGENDA, l.SIGLA_COLIGACAO AS SIGLA_COLIGACAO, l.NOME_COLIGACAO AS NOME_COLIGACAO, l.COMPOSICAO_COLIGACAO AS COMPOSICAO_COLIGACAO, v.QTDE_VOTOS AS QTDE_VOTOS, v.ID_CANDIDATO AS ID_CANDIDATO, v.ID_LEGENDA AS ID_LEGENDA FROM ( SELECT NUMERO_CANDIDATO, UF, NOME_UF, NOME_MICRO, ANO_ELEICAO, DESCRICAO_CARGO, ID_CANDIDATO, CODIGO_MACRO, CODIGO_MICRO, CODIGO_CARGO, NOME_MESO, NOME_MACRO, CODIGO_MESO, NUM_TURNO, DESCRICAO_ELEICAO, SUBSTRING(NUMERO_CANDIDATO, 1, 2) AS NUMERO_PARTIDO, MAX(ID_LEGENDA) AS ID_LEGENDA, SUM(QTDE_VOTOS) AS QTDE_VOTOS FROM votes_micro WHERE (p_cargo = '1') AND p_ano IN ('2014') GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 ) as v LEFT JOIN candidatos as c ON v.ID_CANDIDATO = c.ID_CANDIDATO AND v.ANO_ELEICAO = c.ANO_ELEICAO LEFT JOIN legendas as l ON v.ID_LEGENDA = l.ID_LEGENDA AND v.ANO_ELEICAO = l.ANO_ELEICAO WHERE REGEXP_LIKE(LOWER(c.NOME_CANDIDATO), 'fulano de tal') AND REGEXP_LIKE(LOWER(l.NOME_PARTIDO), 'partido tal') AND c.COD_SIT_TOT_TURNO IN ('1', '2', '3') ORDER BY v.UF ASC, v.NUM_TURNO ASC, l.SIGLA_PARTIDO ASC, c.NOME_CANDIDATO ASC, l.COMPOSICAO_COLIGACAO ASC, l.COMPOSICAO_COLIGACAO ASC

In [8]:
query(table='tse', years=[2014], job=1, reg=6, pol=4)

SELECT CODIGO_CARGO AS CODIGO_CARGO, CODIGO_MICRO AS CODIGO_MICRO, UF AS UF, NOME_UF AS NOME_UF, NOME_MESO AS NOME_MESO, NOME_MICRO AS NOME_MICRO, COD_MUN_TSE AS COD_MUN_TSE, ANO_ELEICAO AS ANO_ELEICAO, DESCRICAO_CARGO AS DESCRICAO_CARGO, NOME_MACRO AS NOME_MACRO, CODIGO_MESO AS CODIGO_MESO, NOME_MUNICIPIO AS NOME_MUNICIPIO, NUM_TURNO AS NUM_TURNO, COD_MUN_IBGE AS COD_MUN_IBGE, CODIGO_MACRO AS CODIGO_MACRO, DESCRICAO_ELEICAO AS DESCRICAO_ELEICAO, SUM(QTD_APTOS) AS QTD_APTOS, SUM(QTD_COMPARECIMENTO) AS QTD_COMPARECIMENTO, SUM(QTD_ABSTENCOES) AS QTD_ABSTENCOES, SUM(QT_VOTOS_NOMINAIS) AS QT_VOTOS_NOMINAIS, SUM(QT_VOTOS_BRANCOS) AS QT_VOTOS_BRANCOS, SUM(QT_VOTOS_NULOS) AS QT_VOTOS_NULOS, SUM(QT_VOTOS_LEGENDA) AS QT_VOTOS_LEGENDA, SUM(QT_VOTOS_ANULADOS_APU_SEP) AS QT_VOTOS_ANULADOS_APU_SEP FROM detalhe_mun WHERE p_ano IN ('2014') AND (p_cargo = '1') GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 ORDER BY UF ASC, NUM_TURNO ASC, COD_MUN_IBGE ASC

In [9]:
query(table='tse', years=[2002], job=1, reg=0, pol=2, only_elected=True)

SELECT v.ANO_ELEICAO AS ANO_ELEICAO, v.NUM_TURNO AS NUM_TURNO, v.DESCRICAO_ELEICAO AS DESCRICAO_ELEICAO, c.SIGLA_UE AS SIGLA_UE, c.DESCRICAO_UE AS DESCRICAO_UE, v.CODIGO_CARGO AS CODIGO_CARGO, v.DESCRICAO_CARGO AS DESCRICAO_CARGO, IF(v.NUMERO_PARTIDO = '95', 'VOTO BRANCO', IF(v.NUMERO_PARTIDO = '96', 'VOTO NULO', c.NOME_CANDIDATO)) AS NOME_CANDIDATO, v.NUMERO_CANDIDATO AS NUMERO_CANDIDATO, c.CPF_CANDIDATO AS CPF_CANDIDATO, c.NOME_URNA_CANDIDATO AS NOME_URNA_CANDIDATO, c.COD_SITUACAO_CANDIDATURA AS COD_SITUACAO_CANDIDATURA, c.DES_SITUACAO_CANDIDATURA AS DES_SITUACAO_CANDIDATURA, l.NUMERO_PARTIDO AS NUMERO_PARTIDO, IF(v.NUMERO_PARTIDO = '95', 'VOTO BRANCO', IF(v.NUMERO_PARTIDO = '96', 'VOTO NULO', l.SIGLA_PARTIDO)) AS SIGLA_PARTIDO, IF(v.NUMERO_PARTIDO = '95', 'VOTO BRANCO', IF(v.NUMERO_PARTIDO = '96', 'VOTO NULO', l.NOME_PARTIDO)) AS NOME_PARTIDO, c.CODIGO_LEGENDA AS CODIGO_LEGENDA, c.SIGLA_LEGENDA AS SIGLA_LEGENDA, c.COMPOSICAO_LEGENDA AS COMPOSICAO_LEGENDA, c.CODIGO_OCUPACAO AS CODIGO_OCUPACAO, c.DESCRICAO_OCUPACAO AS DESCRICAO_OCUPACAO, c.DATA_NASCIMENTO AS DATA_NASCIMENTO, c.NUM_TITULO_ELEITORAL_CANDIDATO AS NUM_TITULO_ELEITORAL_CANDIDATO, c.IDADE_DATA_ELEICAO AS IDADE_DATA_ELEICAO, c.CODIGO_SEXO AS CODIGO_SEXO, c.DESCRICAO_SEXO AS DESCRICAO_SEXO, c.COD_GRAU_INSTRUCAO AS COD_GRAU_INSTRUCAO, c.DESCRICAO_GRAU_INSTRUCAO AS DESCRICAO_GRAU_INSTRUCAO, c.CODIGO_ESTADO_CIVIL AS CODIGO_ESTADO_CIVIL, c.DESCRICAO_ESTADO_CIVIL AS DESCRICAO_ESTADO_CIVIL, c.CODIGO_COR_RACA AS CODIGO_COR_RACA, c.DESCRICAO_COR_RACA AS DESCRICAO_COR_RACA, c.CODIGO_NACIONALIDADE AS CODIGO_NACIONALIDADE, c.DESCRICAO_NACIONALIDADE AS DESCRICAO_NACIONALIDADE, c.SIGLA_UF_NASCIMENTO AS SIGLA_UF_NASCIMENTO, c.CODIGO_MUNICIPIO_NASCIMENTO AS CODIGO_MUNICIPIO_NASCIMENTO, c.NOME_MUNICIPIO_NASCIMENTO AS NOME_MUNICIPIO_NASCIMENTO, c.DESPESA_MAX_CAMPANHA AS DESPESA_MAX_CAMPANHA, c.COD_SIT_TOT_TURNO AS COD_SIT_TOT_TURNO, c.DESC_SIT_TOT_TURNO AS DESC_SIT_TOT_TURNO, c.EMAIL_CANDIDATO AS EMAIL_CANDIDATO, l.TIPO_LEGENDA AS TIPO_LEGENDA, l.SIGLA_COLIGACAO AS SIGLA_COLIGACAO, l.NOME_COLIGACAO AS NOME_COLIGACAO, l.COMPOSICAO_COLIGACAO AS COMPOSICAO_COLIGACAO, v.QTDE_VOTOS AS QTDE_VOTOS, v.ID_CANDIDATO AS ID_CANDIDATO, v.ID_LEGENDA AS ID_LEGENDA FROM ( SELECT CODIGO_CARGO, NUMERO_CANDIDATO, DESCRICAO_CARGO, ANO_ELEICAO, ID_CANDIDATO, NUM_TURNO, DESCRICAO_ELEICAO, SUBSTRING(NUMERO_CANDIDATO, 1, 2) AS NUMERO_PARTIDO, MAX(ID_LEGENDA) AS ID_LEGENDA, SUM(QTDE_VOTOS) AS QTDE_VOTOS FROM votes_uf WHERE (p_cargo = '1') AND p_ano IN ('2002') GROUP BY 1, 2, 3, 4, 5, 6, 7 ) as v LEFT JOIN candidatos as c ON v.ID_CANDIDATO = c.ID_CANDIDATO AND v.ANO_ELEICAO = c.ANO_ELEICAO LEFT JOIN legendas as l ON v.ID_LEGENDA = l.ID_LEGENDA AND v.ANO_ELEICAO = l.ANO_ELEICAO WHERE c.COD_SIT_TOT_TURNO IN ('1', '2', '3') ORDER BY v.NUM_TURNO ASC, l.SIGLA_PARTIDO ASC, c.NOME_CANDIDATO ASC, l.COMPOSICAO_COLIGACAO ASC, l.COMPOSICAO_COLIGACAO ASC

In [10]:
query(table='bem_candidato', years=[2018], uf_filter='AC')

SELECT DATA_GERACAO AS DATA_GERACAO, HORA_GERACAO AS HORA_GERACAO, ANO_ELEICAO AS ANO_ELEICAO, DESCRICAO_ELEICAO AS DESCRICAO_ELEICAO, SIGLA_UF AS SIGLA_UF, SQ_CANDIDATO AS SQ_CANDIDATO, CD_TIPO_BEM_CANDIDATO AS CD_TIPO_BEM_CANDIDATO, DS_TIPO_BEM_CANDIDATO AS DS_TIPO_BEM_CANDIDATO, DETALHE_BEM AS DETALHE_BEM, VALOR_BEM AS VALOR_BEM, DATA_ULTIMA_ATUALIZACAO AS DATA_ULTIMA_ATUALIZACAO, HORA_ULTIMA_ATUALIZACAO AS HORA_ULTIMA_ATUALIZACAO FROM bem_candidato WHERE p_ano IN ('2018') AND SIGLA_UF = 'AC' ORDER BY ANO_ELEICAO ASC, SIGLA_UF ASC, SQ_CANDIDATO ASC